baseurl = "https://darshanime.github.io"
title = "ThinkSpace"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-58520192-1"
enableEmoji = true
copyright = ""
description = "Blog by Darshan Chaudhary"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  twitter = "deathbullet"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

# [[params.menu]]
#   name = "post series"
#   url = "series/"
  

[[params.menu]]
  name = "about"
  url = "about/"
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    respectDoNotTrack = false
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = false
  [privacy.youtube]
    privacyEnhanced = false